#+title: Figures and Tables
#+PROPERTY:header-args R :results output raw :eval never-export :session tabs_figs :wrap export latex :dir . :exports results

* LaTeX packages :noexport:

#+latex_header: \usepackage{booktabs, caption, longtable, colortbl, array}
#+latex_header: \usepackage{tabularx,amsmath,amsfonts,amssymb}
#+latex_header: \usepackage{anyfontsize,multirow}
#+latex_header: \usepackage{pdflscape}

* Global variables :noexport:


#+begin_src R :exports none
selected_countries <- c("ARG", "AUS")

## FIXME: Ideally export as a RDs from the main scripts
all_methods <- c(
  "Net Exports",
  "Attribution",
  "Import Content",
  "Average Import Content"
)

benchmark_meth <- "Import Content"
benchmark_var <- "CDX"
snd_bst <- "Average Import Content"


others <- setdiff(all_methods, benchmark_meth)

use_line <- TRUE

include_graphics <- function(
    main,
    extension = "pdf",
    figs_dir = "./figs",
    width = "\\textwidth"
) {

  file_path <- file.path(figs_dir, paste0(main, ".", extension))

  # Build graphics options string
  graphics_options <- paste0("[width=", width, "]")

  # Construct the LaTeX command
  latex_cmd <- paste0("\\includegraphics", graphics_options, "{", file_path, "}")

  # Return as raw LaTeX (works in knitr/rmarkdown)
  latex_cmd <- knitr::asis_output(latex_cmd) |>
    as.character()
  cat(latex_cmd, sep = "\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
#+end_export


* Figures

** Growth Decomposition

#+begin_src R
for (iso  in selected_countries) {
  base_name <- "Growth_Decomp_Method_"
  fname <- paste0(base_name, iso)
  cat("\\begin{figure}[t]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{Growth Decomposition for ", iso, "}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/Growth_Decomp_Method_ARG.pdf}
\caption{Growth Decomposition for ARG}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/Growth_Decomp_Method_AUS.pdf}
\caption{Growth Decomposition for AUS}
\end{figure}
#+end_export


** Paired Comparison


#+begin_src R

if (use_line) {
  prefix <- "Line"
} else {
  prefix <- "Dot"
}

for (iso  in selected_countries) {
  for (alt in others) {
    cat("\\begin{figure}[H]\n")
    cat("\\centering\n")
    base_name <- paste0(
      prefix, "Diff_",
      alt,
      "_",
      benchmark_meth,
      "_"
    )
    base_name <- base_name |>
      stringr::str_remove_all(" ")

    fname <- paste0(base_name, iso)
    include_graphics(main = fname)
    cat(paste0("\\caption{", alt, " vs. ", benchmark_meth, " for ", iso,  "}\n"))
    cat("\\end{figure}\n\n")
  }
}

for (iso  in selected_countries) {
    cat("\\begin{figure}[H]\n")
    cat("\\centering\n")
    base_name <- paste0(
      "DistDiff_",
      benchmark_meth,
      "_"
    )
    base_name <- base_name |>
      stringr::str_remove_all(" ")

    fname <- paste0(base_name, iso)
    include_graphics(main = fname)
    cat(paste0("\\caption{Scaled distribution of divergences in respect to ", benchmark_meth, " for ", iso,  "}\n"))
    cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_ARG.pdf}
\caption{Net Exports vs. Import Content for ARG}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_ARG.pdf}
\caption{Attribution vs. Import Content for ARG}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_ARG.pdf}
\caption{Average Import Content vs. Import Content for ARG}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_AUS.pdf}
\caption{Net Exports vs. Import Content for AUS}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_AUS.pdf}
\caption{Attribution vs. Import Content for AUS}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_AUS.pdf}
\caption{Average Import Content vs. Import Content for AUS}
\end{figure}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_ARG.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for ARG}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_AUS.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for AUS}
\end{figure}
#+end_export

** CDX vs CDD


#+begin_src R
for (iso  in selected_countries) {
  base_name <- "Contrib_CDD_CDX_"
  fname <- paste0(base_name, iso)
  cat("\\begin{figure}[t]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{CDD and CDX contribution for ", iso, "}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/Contrib_CDD_CDX_ARG.pdf}
\caption{CDD and CDX contribution for ARG}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/Contrib_CDD_CDX_AUS.pdf}
\caption{CDD and CDX contribution for AUS}
\end{figure}
#+end_export

** Import coefficients

*** Boxplots


#+begin_src R
for (iso  in selected_countries) {
  base_name <- "ImpCoef_BoxPlot_"
  fname <- paste0(base_name, iso)
  cat("\\begin{figure}[t]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{Import Coefficient Boxplots for ", iso, "}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_ARG.pdf}
\caption{Import Coefficient Boxplots for ARG}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_AUS.pdf}
\caption{Import Coefficient Boxplots for AUS}
\end{figure}
#+end_export


*** Time-series


#+begin_src R
for (iso  in selected_countries) {
  base_name <- "ImpCoef_TimeSeries_"
  fname <- paste0(base_name, iso)
  cat("\\begin{figure}[t]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{Import Coefficient Boxplots for ", iso, "}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_TimeSeries_ARG.pdf}
\caption{Import Coefficient Boxplots for ARG}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_TimeSeries_AUS.pdf}
\caption{Import Coefficient Boxplots for AUS}
\end{figure}
#+end_export

* Tables

** Metrics comparing methods


#+begin_src R
for (iso  in selected_countries) {
  tmp_sec <- paste0(
    "\\subsubsection*{",
    "Dissimilarity measures in respect to ",
    benchmark_meth,
    " for ",
    benchmark_var,
    " variable for ",
    iso,
    "}\n"
)

  cat(tmp_sec)
  
  basename <- paste0(
    "./tabs/",
    iso,
    "_",
    benchmark_meth,
    "_",
    benchmark_var,
    ".tex"
  ) |>
    stringr::str_remove_all(" ")
  tmp_include <- paste0(
    "\\include{",
    basename,
    "}\n"
  )
  cat(tmp_include)
}
#+end_src

#+RESULTS:
#+begin_export latex
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for ARG}
\include{./tabs/ARG_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for AUS}
\include{./tabs/AUS_ImportContent_CDX.tex}
#+end_export
