#+options: toc:nil
#+title: Figures and Tables
#+PROPERTY:header-args R :results output raw :eval never-export :session tabs_figs :wrap export latex :dir . :exports results

* LaTeX packages :noexport:

#+latex_header: \usepackage{booktabs, caption, longtable, colortbl, array}
#+latex_header: \usepackage{tabularx,amsmath,amsfonts,amssymb}
#+latex_header: \usepackage{anyfontsize,multirow}
#+latex_header: \usepackage{pdflscape}
#+latex_header: \usepackage{threeparttablex}

* Global variables :noexport:


#+begin_src R :exports none
country_groups <- readRDS("./objs/country_groups.rds")

groups <- names(country_groups)

## FIXME: Ideally export as a RDs from the main scripts
all_methods <- c(
  "Net Exports",
  "Attribution",
  "Import Content",
  "Average Import Content"
)

benchmark_meth <- "Import Content"
benchmark_var <- "CDX"
snd_bst <- "Average Import Content"


others <- setdiff(all_methods, benchmark_meth)

use_line <- TRUE

include_graphics <- function(
    main,
    extension = "pdf",
    figs_dir = "./figs",
    width = "\\textwidth"
) {

  file_path <- file.path(figs_dir, paste0(main, ".", extension))

  # Build graphics options string
  graphics_options <- paste0("[width=", width, "]")

  # Construct the LaTeX command
  latex_cmd <- paste0("\\includegraphics", graphics_options, "{", file_path, "}")

  # Return as raw LaTeX (works in knitr/rmarkdown)
  latex_cmd <- knitr::asis_output(latex_cmd) |>
    as.character()
  cat(latex_cmd, sep = "\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
#+end_export


* Figures

** Growth Decomposition

#+begin_src R
for (group  in groups) {
  base_name <- "Growth_Decomp_"
  fname <- paste0(base_name, group)
  fname <- fname |>
    stringr::str_remove_all(" ")
  cat("\\begin{figure}[H]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{Growth Decomposition for ", group, " countries}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/Growth_Decomp_Developed.pdf}
\caption{Growth Decomposition for Developed countries}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/Growth_Decomp_Developing.pdf}
\caption{Growth Decomposition for Developing countries}
\end{figure}
#+end_export


** Paired Comparison :noexport:


#+begin_src R :eval no

if (use_line) {
  prefix <- "Line"
} else {
  prefix <- "Dot"
}

for (iso  in selected_countries) {
  for (alt in others) {
    cat("\\begin{figure}[H]\n")
    cat("\\centering\n")
    base_name <- paste0(
      prefix, "Diff_",
      alt,
      "_",
      benchmark_meth,
      "_"
    )
    base_name <- base_name |>
      stringr::str_remove_all(" ")

    fname <- paste0(base_name, iso)
    include_graphics(main = fname)
    cat(paste0("\\caption{", alt, " vs. ", benchmark_meth, " for ", iso,  "}\n"))
    cat("\\end{figure}\n\n")
  }
}

for (iso  in selected_countries) {
    cat("\\begin{figure}[H]\n")
    cat("\\centering\n")
    base_name <- paste0(
      "DistDiff_",
      benchmark_meth,
      "_"
    )
    base_name <- base_name |>
      stringr::str_remove_all(" ")

    fname <- paste0(base_name, iso)
    include_graphics(main = fname)
    cat(paste0("\\caption{Scaled distribution of divergences in respect to ", benchmark_meth, " for ", iso,  "}\n"))
    cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_CAN.pdf}
\caption{Net Exports vs. Import Content for CAN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_CAN.pdf}
\caption{Attribution vs. Import Content for CAN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_CAN.pdf}
\caption{Average Import Content vs. Import Content for CAN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_FRA.pdf}
\caption{Net Exports vs. Import Content for FRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_FRA.pdf}
\caption{Attribution vs. Import Content for FRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_FRA.pdf}
\caption{Average Import Content vs. Import Content for FRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_DEU.pdf}
\caption{Net Exports vs. Import Content for DEU}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_DEU.pdf}
\caption{Attribution vs. Import Content for DEU}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_DEU.pdf}
\caption{Average Import Content vs. Import Content for DEU}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_ITA.pdf}
\caption{Net Exports vs. Import Content for ITA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_ITA.pdf}
\caption{Attribution vs. Import Content for ITA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_ITA.pdf}
\caption{Average Import Content vs. Import Content for ITA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_JPN.pdf}
\caption{Net Exports vs. Import Content for JPN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_JPN.pdf}
\caption{Attribution vs. Import Content for JPN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_JPN.pdf}
\caption{Average Import Content vs. Import Content for JPN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_GBR.pdf}
\caption{Net Exports vs. Import Content for GBR}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_GBR.pdf}
\caption{Attribution vs. Import Content for GBR}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_GBR.pdf}
\caption{Average Import Content vs. Import Content for GBR}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_USA.pdf}
\caption{Net Exports vs. Import Content for USA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_USA.pdf}
\caption{Attribution vs. Import Content for USA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_USA.pdf}
\caption{Average Import Content vs. Import Content for USA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_BRA.pdf}
\caption{Net Exports vs. Import Content for BRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_BRA.pdf}
\caption{Attribution vs. Import Content for BRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_BRA.pdf}
\caption{Average Import Content vs. Import Content for BRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_RUS.pdf}
\caption{Net Exports vs. Import Content for RUS}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_RUS.pdf}
\caption{Attribution vs. Import Content for RUS}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_RUS.pdf}
\caption{Average Import Content vs. Import Content for RUS}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_IND.pdf}
\caption{Net Exports vs. Import Content for IND}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_IND.pdf}
\caption{Attribution vs. Import Content for IND}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_IND.pdf}
\caption{Average Import Content vs. Import Content for IND}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_CHN.pdf}
\caption{Net Exports vs. Import Content for CHN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_CHN.pdf}
\caption{Attribution vs. Import Content for CHN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_CHN.pdf}
\caption{Average Import Content vs. Import Content for CHN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_ZAF.pdf}
\caption{Net Exports vs. Import Content for ZAF}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_ZAF.pdf}
\caption{Attribution vs. Import Content for ZAF}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_ZAF.pdf}
\caption{Average Import Content vs. Import Content for ZAF}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_SWE.pdf}
\caption{Net Exports vs. Import Content for SWE}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_SWE.pdf}
\caption{Attribution vs. Import Content for SWE}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_SWE.pdf}
\caption{Average Import Content vs. Import Content for SWE}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_NLD.pdf}
\caption{Net Exports vs. Import Content for NLD}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_NLD.pdf}
\caption{Attribution vs. Import Content for NLD}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_NLD.pdf}
\caption{Average Import Content vs. Import Content for NLD}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_MEX.pdf}
\caption{Net Exports vs. Import Content for MEX}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_MEX.pdf}
\caption{Attribution vs. Import Content for MEX}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_MEX.pdf}
\caption{Average Import Content vs. Import Content for MEX}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_NetExports_ImportContent_KOR.pdf}
\caption{Net Exports vs. Import Content for KOR}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_Attribution_ImportContent_KOR.pdf}
\caption{Attribution vs. Import Content for KOR}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/LineDiff_AverageImportContent_ImportContent_KOR.pdf}
\caption{Average Import Content vs. Import Content for KOR}
\end{figure}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_CAN.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for CAN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_FRA.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for FRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_DEU.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for DEU}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_ITA.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for ITA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_JPN.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for JPN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_GBR.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for GBR}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_USA.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for USA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_BRA.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for BRA}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_RUS.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for RUS}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_IND.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for IND}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_CHN.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for CHN}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_ZAF.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for ZAF}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_SWE.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for SWE}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_NLD.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for NLD}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_MEX.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for MEX}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/DistDiff_ImportContent_KOR.pdf}
\caption{Scaled distribution of divergences in respect to Import Content for KOR}
\end{figure}
#+end_export

** CDX vs CDD


#+begin_src R
for (group  in groups) {
  base_name <- "Contrib_CDD_CDX_"
  fname <- paste0(base_name, group)
  cat("\\begin{figure}[H]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{CDD and CDX contribution for ", group, " countries}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/Contrib_CDD_CDX_Developed.pdf}
\caption{CDD and CDX contribution for Developed countries}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/Contrib_CDD_CDX_Developing.pdf}
\caption{CDD and CDX contribution for Developing countries}
\end{figure}
#+end_export

** Import coefficients

*** Boxplots :noexport:


#+begin_src R :eval no
for (iso  in selected_countries) {
  base_name <- "ImpCoef_BoxPlot_"
  fname <- paste0(base_name, iso)
  cat("\\begin{figure}[H]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{Import Coefficient Boxplots for ", iso, "}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_CAN.pdf}
\caption{Import Coefficient Boxplots for CAN}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_FRA.pdf}
\caption{Import Coefficient Boxplots for FRA}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_DEU.pdf}
\caption{Import Coefficient Boxplots for DEU}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_ITA.pdf}
\caption{Import Coefficient Boxplots for ITA}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_JPN.pdf}
\caption{Import Coefficient Boxplots for JPN}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_GBR.pdf}
\caption{Import Coefficient Boxplots for GBR}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_USA.pdf}
\caption{Import Coefficient Boxplots for USA}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_BRA.pdf}
\caption{Import Coefficient Boxplots for BRA}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_RUS.pdf}
\caption{Import Coefficient Boxplots for RUS}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_IND.pdf}
\caption{Import Coefficient Boxplots for IND}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_CHN.pdf}
\caption{Import Coefficient Boxplots for CHN}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_ZAF.pdf}
\caption{Import Coefficient Boxplots for ZAF}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_SWE.pdf}
\caption{Import Coefficient Boxplots for SWE}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_NLD.pdf}
\caption{Import Coefficient Boxplots for NLD}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_MEX.pdf}
\caption{Import Coefficient Boxplots for MEX}
\end{figure}

\begin{figure}[t]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_BoxPlot_KOR.pdf}
\caption{Import Coefficient Boxplots for KOR}
\end{figure}
#+end_export


*** Time-series


#+begin_src R
for (group  in groups) {
  base_name <- "ImpCoef_TimeSeries_"
  fname <- paste0(base_name, group)
  cat("\\begin{figure}[H]\n")
  cat("\\centering\n")
  include_graphics(main = fname)
  cat(paste0("\\caption{Import Coefficient Boxplots for ", group, " countries}\n"))
  cat("\\end{figure}\n\n")
}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_TimeSeries_Developed.pdf}
\caption{Import Coefficient Boxplots for Developed countries}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/ImpCoef_TimeSeries_Developing.pdf}
\caption{Import Coefficient Boxplots for Developing countries}
\end{figure}
#+end_export


* Comparative differences


#+begin_export latex
\newpage
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{./figs/Differences_Database_All.pdf}
\caption{Dissimilarity between Import Content method and alternative methods (all countries)}
\end{figure}
#+end_export


* Tables

** Metrics comparing methods (Selected countries) :noexport:


#+begin_src R
for (iso  in selected_countries) {
  tmp_sec <- paste0(
    "\\subsubsection*{",
    "Dissimilarity measures in respect to ",
    benchmark_meth,
    " for ",
    benchmark_var,
    " variable for ",
    iso,
    "}\n"
)

  cat(tmp_sec)
  
  basename <- paste0(
    "./tabs/",
    iso,
    "_",
    benchmark_meth,
    "_",
    benchmark_var,
    ".tex"
  ) |>
    stringr::str_remove_all(" ")
  tmp_include <- paste0(
    "\\include{",
    basename,
    "}\n"
  )
  cat(tmp_include)
}
#+end_src

#+RESULTS:
#+begin_export latex
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for FRA}
\include{./tabs/FRA_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for DEU}
\include{./tabs/DEU_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for ITA}
\include{./tabs/ITA_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for JPN}
\include{./tabs/JPN_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for GBR}
\include{./tabs/GBR_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for USA}
\include{./tabs/USA_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for BRA}
\include{./tabs/BRA_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for IND}
\include{./tabs/IND_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for CHN}
\include{./tabs/CHN_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for SWE}
\include{./tabs/SWE_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for NLD}
\include{./tabs/NLD_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for MEX}
\include{./tabs/MEX_ImportContent_CDX.tex}
\subsubsection*{Dissimilarity measures in respect to Import Content for CDX variable for KOR}
\include{./tabs/KOR_ImportContent_CDX.tex}
#+end_export

** All countries

#+begin_export latex
\include{./tabs/All_Metrics.tex}
#+end_export
