library(tidyverse)

## Data generated by André
## FIXME: Genate this table internally
load("../results/NIOTs_resultados.rdata")

countrys <- NIOTs |> names()

### FIXME: In case of generalization, ajust here to use ISO code and save as a generic object
USA <- NIOTs[["USA"]]
tbls <- USA |> names()
years <- USA[[1]] |> names()

first_year <- years[1]
last_year <- tail(years, 1)

