library(tidyverse)

## Data generated by André
## FIXME: Genate this table internally
load("../results/NIOTs_resultados.rdata")

## Initiate some general information
countries <- NIOTs |> names()
country <- NIOTs[[countries[1]]]
tbls <- country |> names()
years <- country[[1]] |> names()
first_year <- years[1]
last_year <- tail(years, 1)

country <- NULL

results <- list()

## NOTE: Got just a generic csv with this information
oecd <- readr::read_csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/refs/heads/main/data/oecd.csv") |>
  select(Code) |>
  as.vector() |>
  unlist(use.names = FALSE)


for (country in oecd) {
  list(country) <- NULL

  data <- NIOTs[[country]]
}

### FIXME: In case of generalization, ajust here to use ISO code and save as a generic object
## USA <- NIOTs[["USA"]]
